apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: sql
  name: mysql
  namespace:  webapplication
spec:
  containers:
  - name: mysqldb
    image: 019820965776.dkr.ecr.us-east-1.amazonaws.com/assignment2:appdb1.0
    ports: 
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value : janki
