apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels :
    app: mysql
  name: mysql-repica
  namespace:  webapplication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 019820965776.dkr.ecr.us-east-1.amazonaws.com/assignment2:appdb1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value : janki
        ports: 
        - containerPort: 8080
          protocol: TCP
